//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MATH.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MATH.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _1UP {
            get {
                object obj = ResourceManager.GetObject("_1UP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _88x31 {
            get {
                object obj = ResourceManager.GetObject("_88x31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bgToadGuess {
            get {
                object obj = ResourceManager.GetObject("bgToadGuess", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BowserNote {
            get {
                object obj = ResourceManager.GetObject("BowserNote", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chest {
            get {
                object obj = ResourceManager.GetObject("chest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dead {
            get {
                object obj = ResourceManager.GetObject("dead", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap intro {
            get {
                object obj = ResourceManager.GetObject("intro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap levelClear {
            get {
                object obj = ResourceManager.GetObject("levelClear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Mario3_Flying {
            get {
                object obj = ResourceManager.GetObject("Mario3_Flying", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MarioBig {
            get {
                object obj = ResourceManager.GetObject("MarioBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap marioGo {
            get {
                object obj = ResourceManager.GetObject("marioGo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MarioNote {
            get {
                object obj = ResourceManager.GetObject("MarioNote", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap musicBox {
            get {
                object obj = ResourceManager.GetObject("musicBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sm64_thank_you {
            get {
                return ResourceManager.GetStream("sm64_thank_you", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sm64Mario {
            get {
                return ResourceManager.GetStream("sm64Mario", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream snd1UP {
            get {
                return ResourceManager.GetStream("snd1UP", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sndDeath {
            get {
                return ResourceManager.GetStream("sndDeath", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sndLevelClear {
            get {
                return ResourceManager.GetStream("sndLevelClear", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sndTail {
            get {
                return ResourceManager.GetStream("sndTail", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sndThreeCards {
            get {
                return ResourceManager.GetStream("sndThreeCards", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sndTreasureBox {
            get {
                return ResourceManager.GetStream("sndTreasureBox", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sndWinner {
            get {
                return ResourceManager.GetStream("sndWinner", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tail {
            get {
                object obj = ResourceManager.GetObject("tail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap threeCards {
            get {
                object obj = ResourceManager.GetObject("threeCards", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toadGo {
            get {
                object obj = ResourceManager.GetObject("toadGo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap winner {
            get {
                object obj = ResourceManager.GetObject("winner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
